# Make sure you're using the correct MATERIAL name for your server's version : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# You're able to use placeholders for names that are not fully capitalized. To use, just add a "_l" behind placeholders, e.g, %companion_l%, %active_companion_l%.

settings:
  # Check if the plugin is up to date.
  versionChecking: true
  # Set the keyword to cancel chat actions like changing weapons/name.
  cancelKeyWord: "cancel"
  # Plays an action bar of the Companion's name when it's equipped.
  actionBarMessage: true
  # Set what's the max upgradable ability level - It's advisable to put a level lower than 5.
  maxAbilityLevel: 3
  # Set the max name length a player can set to.
  maxNameLength: 10
  abilityMaxedOutItem: GUNPOWDER
  # The range determines how far other players are able to see someone's Companion at. Change at your own risk, a higher range might result in more resourced used.
  packetSearchRange: 10, 10, 10
  # companionTalk is removed temporarily (hopefully).
  companionTalk:
    - "<gray>Heh. That tickles!"
    - "<gray>Get your hands away from me!"
    - "<gray>What?"
    - "<gray>Yes?"
    - "<gray>Knock, knock! .. Who's there?"
    - "<gray>What am I?"
    - "<gray>... Where am I?"
  # interactCooldown is counted by seconds.    
  interactCooldown: 3
  # Set how frequent should the plugin save its necessary files.(in minutes)
  saveTime: 60
  vanish:
    perms: essentials.vanish
    commands: /v, /vanish
  
  # Set which names that you don't want players' companions having. 
  # companions.admin.blacklist - allows you to override the blacklist system using this permission node.
  blacklistedNames:
    - "dick"
    - "fuck"
  # Set which worlds you do not want Companions to be used in.  
  disabledWorlds:
    - world1
    - world2
  # Set which line to not show in the owned Companion ItemStacks
  replacedOwnedLores:
    - "<gold><b>LEFT CLICK </b><gray>to purchase the <gold>%companion% Companion<gray>!"
    - "<gold>PRICE: <yellow>$%price%"
  
  # true: Kick player if cache is not loaded for them properly. (To ensure all Companions Data are loaded for the player)
  ensureCache: true
    
database:
  use: false
  hostname: localhost
  port: 3306
  username: "root"
  password: ""
  databaseName: "companions"
  tablePrefix: "companions_"
    
items:
  companionToken:
    name: "<gold><b>COMPANION TOKEN</b>"
    type: GHAST_TEAR
    description: 
      - ""
      - "<gold><b>RIGHT CLICK </b><gray>on a block"
      - " to redeem your mystery Companion!"
    particleAnimation: EXPLOSION_LARGE
    soundOnUse: BLOCK_BEACON_POWER_SELECT
    
GUI:
  goBack:
    type: BARRIER
    amount: 1
    name: "<gold><b>PREVIOUS PAGE</b>"
    slot: 45
    description:
      - " "
      - "<gold><b>LEFT CLICK </b><gray>to go back to the previous page."    
  nextPage:
    type: ARROW
    amount: 1
    name: "<gold><b>NEXT PAGE</b>"
    slot: 53
    description:
      - " "
      - "<gold><b>LEFT CLICK </b><gray>to go back to the next page."  
  open-companions:
    title: "<gold><b>COMPANIONS</b>"
    size: 9
    openSound: BLOCK_BEACON_ACTIVATE
    
    items:
      companion-shop:
        type: PUFFERFISH_SPAWN_EGG
        amount: 1
        name: '<gold>PURCHASE COMPANIONS'
        slot: 0
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to view a list of companions"
          - "<gray>that you can purchase!"
      owned-companions:
        type: CHEST
        amount: 1
        name: '<gold>OWNED COMPANIONS'
        slot: 4
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to view a list of companions"
          - "<gray>that you own!"   
      upgrade-abilities:
        type: PAPER
        amount: 1
        name: '<gold>UPGRADE ABILITIES'
        slot: 8
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to view a list of upgrades"
          - "<gray>that you can do on your companion!"                   
          

  open-companions-shop:
    title: "<gold><b>COMPANIONS SHOP</b>"
    size: 54
    openSound: BLOCK_BEACON_ACTIVATE     
    
    # Set which menu it goes back to when you reach to page 0. Great for creating custom menus.
    goBackCommand: "companions"      
        
  owned-companions:
    title: "<gold><b>OWNED COMPANIONS</b>"
    size: 54
    openSound: BLOCK_BEACON_ACTIVATE    
    
    # Set which menu it goes back to when you reach to page 0. Great for creating custom menus.
    goBackCommand: "companions"  
    
    items:
      companionDetails:
        type: PAPER
        amount: 1
        name: "<gold><b>COMPANION DETAILS</b>"
        slot: 0
        description:
          - " "
          - "<gold>ACTIVE COMPANION: <yellow>%active_companion%"
          - "<gold>COMPANION COINS: <yellow>%companions_coins%"
          - ""
          - "<gold><b>LEFT CLICK </b><gray>to remove your active companion."   
  upgrade-abilities:
    title: "<gold><b>UPGRADING..</b>"
    size: 9
    openSound: BLOCK_BEACON_ACTIVATE  
    
    # Set which menu it goes back to when you reach to page 0. Great for creating custom menus.
    goBackCommand: "companions"    
    
    items:
      upgradeDetails:
        type: PAPER
        amount: 1
        name: "<gold><b>UPGRADE DETAILS</b>"
        slot: 1
        description:
          - " "
          - "<gold>You are currently upgrading <yellow>%active_companion%"    
          - " "
          - "<gold><b>DETAILS</b>"
          - "<yellow>NAME: <gold>%companion_name%"               
          - "<yellow>LEVEL: <gold>%companion_level%"     
          - ""
          - "<gray>(You can only upgrade your active companion!)"
      goBack:
        type: BARRIER
        amount: 1
        name: "<gold><b>PREVIOUS PAGE</b>"
        slot: 0
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to go back to the previous page."          
      abilityLevel:
        type: EXPERIENCE_BOTTLE
        amount: 1
        maxedName: "<gold><b>ABILITY MAXED OUT</b>"
        name: "<gold><b>UPGRADE ABILITY LEVEL</b>"
        slot: 3
        price: 100000
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to upgrade your ability level!"
          - "<gold><b>RIGHT CLICK </b><gray> to lower your ability level!"
          - " "
          - "<gold>PRICE: <yellow>$100,000"    
        maxedDescription:   
          - " "
          - "<gray>You can no longer upgrade your active companion"   
          - ""
          - "<gold><b>RIGHT CLICK</b><gray> to lower your ability level!"
          - " "
          - "<gold>PRICE: <yellow>$100,000"              
      renameCompanion:
        type: NAME_TAG
        amount: 1
        name: "<gold><b>RENAME COMPANION</b>"
        slot: 4
        price: 25000
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to rename your companion!"
          - " "
          - "<gold>PRICE: <yellow>$25,000"         
      hideCompanionName:
        type: MAP
        amount: 1
        name: "<gold><b>HIDE COMPANION'S NAME</b>"
        slot: 5
        price: 2000
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to hide your companion's name!"
          - " "
          - "<gray>(If already bought, this perk reshows the companion name)"
          - "<gold>PRICE: <yellow>$2,000"      
      changeWeapon:
        type: DIAMOND_SWORD
        amount: 1
        name: "<gold><b>CHANGE COMPANION'S WEAPON</b>"
        slot: 6
        price: 6000
        description:
          - " "
          - "<gold><b>LEFT CLICK </b><gray>to change your companion's weapon!"
          - " "
          - "<gold>PRICE: <yellow>$6,000"
  player-details:
    title: "<gold><b>VIEWING </b><yellow>%target%'S<gold><b> DETAILS..</b>"
    openSound: BLOCK_BEACON_ACTIVATE    
    items:
      companionDetails:
        description:
          - " "
          - "<gold>ACTIVE COMPANION: <yellow>%active_companion%"  
          - "<gold>COMPANION COINS: <yellow>%companions_coins%"
       
    